2024-07-04 16:32:05,208 - process_case_info_util.py-ERROR - 'epic'[0m
